# pipeline config ---------------------------------------------------------------------------------

# please adjust content of these files, though their paths should be constants.
FASTQ_SCREEN_CONFIG: "data/config/fastq_screen_config.tsv"
MULTIQC_CONFIG: "data/config/multiqc_config.yaml"
DESEQ2_CONFIG: "data/config/deseq2_config.tsv"

# read alignment + preprocessing ------------------------------------------------------------------

GENOME: "/home/groups/MaxsonLab/indices/mm10/mm10.fa"
ASSEMBLY: "mm10" # [hg38, mm10]

# Forbidden regions of the genome for read alignment and analysis
BANLIST: "/home/groups/MaxsonLab/indices/mm10/mm10.blacklist.v2.bed"

# peak calling ------------------------------------------------------------------------------------

# number of times a peak needs to appear across samples in one condition. helps build consensus peak.
N_INTERSECTS: 2

# size of the genome for macs2 peak calling
GSIZE: "2.7e9"

# differential analysis ---------------------------------------------------------------------------

# filter for results with pval less than <padj_cutoff>
padj_cutoff: 0.05
