# pipeline config ---------------------------------------------------------------------------------
FASTQ_SCREEN_CONFIG: config/fastq_screen_config.tsv
MULTIQC_CONFIG: config/multiqc_config.yaml
DESEQ2_CONFIG: config/deseq2_config.tsv
DIFFBIND_CONFIG: config/diffbind_config.csv
CHROM_SIZES: config/mm10.chrom.sizes # config/hg38.chrom.sizes

# read alignment + preprocessing ------------------------------------------------------------------
GENOME: /home/groups/MaxsonLab/indices/mm10/mm10.fa # /home/groups/MaxsonLab/indices/GRch38/bowtie2/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta
ASSEMBLY: mm10 # hg38

# Forbidden regions of the genome for read alignment and analysis
BANLIST: config/mm10.blacklist.v2.bed # config/hg38.blacklist.v2.bed

# peak calling ------------------------------------------------------------------------------------
# number of times a peak needs to appear across biological replicates in one condition
# to qualify to become a consensus peak. Consensus peak is the union of <N_INTERSECTS> peaks.
N_INTERSECTS: 2

# differential analysis ---------------------------------------------------------------------------
# filter for results with pval less than <padj_cutoff>
padj_cutoff: 0.05

