name: atac_seq-test

uses: snakemake/snakemake-github-action@v1.22.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# with:
#   directory: '.test'
#   snakefile: 'Snakefile'
#   args: '-j 8 --use-conda'

jobs:
  test-atac-seq:
    runs-on: ubuntu-latest
    steps:
      run: |
      echo hello world
      python scripts/make_differential_configs.py
      snakemake -j 8 --use-conda --directory .test