name: atac-seq-test

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  test-atac-seq:
    runs-on: ubuntu-latest
    steps:
      - name: 1 - Checking out atac_seq
        uses: actions/checkout@v2

      - name: 2 - Installing Conda and SnakeMake
        uses: conda-incubator/setup-miniconda@v2
        with:
            activate-environment: snakemake
            environment-file: .test/snakemake.5.32.yaml

      - name: 3 - Activate Conda Environment
        run: |
            pwd
            ls
            tree
            conda init bash
            source ~/.bashrc
            source activate snakemake
            conda info
            conda list

      # - name: 4 - Prepare the Snake
      #   run: |
      #     snakemake -j 1 -np
      #     snakemake -j 2 --use-conda --conda-frontend mamba --conda-create-envs-only

      # - name: 5 - Run the Snake
      #   run: snakemake -j 2 --use-conda --directory .test
