name: atac-seq-test

uses: snakemake/snakemake-github-action@v1.22.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# with:
#   directory: '.test'
#   snakefile: 'Snakefile'
#   args: '-j 8 --use-conda'

jobs:
  test-atac-seq:
    runs-on: ubuntu-latest
    steps:
      - name: 1 - Checking out atac_seq
        uses: actions/checkout@v2

      - name: 2 - Installing Conda and SnakeMake
        uses: conda-incubator/setup-miniconda@v2
        with:
            activate-environment: snakemake
            environment-file: .test/snakemake.5.32.yaml
